/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

/**
 *
 * @author Prashan
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Slotlbl1 = new javax.swing.JLabel();
        Slotlbl6 = new javax.swing.JLabel();
        Slotlbl2 = new javax.swing.JLabel();
        Slotlbl7 = new javax.swing.JLabel();
        Slotlbl4 = new javax.swing.JLabel();
        Slotlbl3 = new javax.swing.JLabel();
        Slotlbl8 = new javax.swing.JLabel();
        Slotlbl9 = new javax.swing.JLabel();
        Slotlbl15 = new javax.swing.JLabel();
        Slotlbl14 = new javax.swing.JLabel();
        Slotlbl12 = new javax.swing.JLabel();
        Slotlbl5 = new javax.swing.JLabel();
        Slotlbl13 = new javax.swing.JLabel();
        Slotlbl10 = new javax.swing.JLabel();
        Slotlbl11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Slotcmbbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Vehiclecmbbox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Startdate = new org.jdesktop.swingx.JXDatePicker();
        Enddate = new org.jdesktop.swingx.JXDatePicker();
        jLabel22 = new javax.swing.JLabel();
        reserveimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1205, 800));
        setPreferredSize(new java.awt.Dimension(1205, 800));
        setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(1205, 771));
        jPanel2.setMinimumSize(new java.awt.Dimension(1205, 771));
        jPanel2.setPreferredSize(new java.awt.Dimension(1205, 771));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(null);

        Slotlbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/available (2).png"))); // NOI18N
        jPanel2.add(Slotlbl1);
        Slotlbl1.setBounds(8, 180, 100, 40);

        Slotlbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/available (2).png"))); // NOI18N
        jPanel2.add(Slotlbl6);
        Slotlbl6.setBounds(534, 180, 100, 40);

        Slotlbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl2.setText("jLabel2");
        jPanel2.add(Slotlbl2);
        Slotlbl2.setBounds(112, 180, 100, 40);

        Slotlbl7.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl7.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl7.setText("jLabel4");
        jPanel2.add(Slotlbl7);
        Slotlbl7.setBounds(640, 180, 100, 40);

        Slotlbl4.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl4.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl4.setText("jLabel4");
        jPanel2.add(Slotlbl4);
        Slotlbl4.setBounds(325, 180, 100, 40);

        Slotlbl3.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl3.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl3.setText("jLabel4");
        jPanel2.add(Slotlbl3);
        Slotlbl3.setBounds(218, 180, 100, 40);

        Slotlbl8.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl8.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl8.setText("jLabel4");
        jPanel2.add(Slotlbl8);
        Slotlbl8.setBounds(745, 180, 100, 40);

        Slotlbl9.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl9.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable.png"))); // NOI18N
        Slotlbl9.setText("jLabel4");
        jPanel2.add(Slotlbl9);
        Slotlbl9.setBounds(850, 180, 100, 40);

        Slotlbl15.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl15.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl15.setText("jLabel4");
        jPanel2.add(Slotlbl15);
        Slotlbl15.setBounds(90, 470, 100, 40);

        Slotlbl14.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl14.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl14.setText("jLabel4");
        jPanel2.add(Slotlbl14);
        Slotlbl14.setBounds(90, 570, 100, 40);

        Slotlbl12.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl12.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl12.setText("jLabel4");
        jPanel2.add(Slotlbl12);
        Slotlbl12.setBounds(770, 670, 100, 40);

        Slotlbl5.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl5.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl5.setText("jLabel4");
        jPanel2.add(Slotlbl5);
        Slotlbl5.setBounds(430, 180, 100, 40);

        Slotlbl13.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl13.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl13.setText("jLabel4");
        jPanel2.add(Slotlbl13);
        Slotlbl13.setBounds(90, 670, 100, 40);

        Slotlbl10.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl10.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl10.setText("jLabel4");
        jPanel2.add(Slotlbl10);
        Slotlbl10.setBounds(770, 470, 100, 40);

        Slotlbl11.setBackground(new java.awt.Color(0, 204, 0));
        Slotlbl11.setForeground(new java.awt.Color(204, 255, 102));
        Slotlbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/unavailable (1).png"))); // NOI18N
        Slotlbl11.setText("jLabel4");
        jPanel2.add(Slotlbl11);
        Slotlbl11.setBounds(770, 570, 100, 40);

        jLabel17.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel17.setText("RESERVATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel17)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 1210, 70);

        Slotcmbbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Slotcmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SLOT :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("VEHICLE :");

        Vehiclecmbbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Vehiclecmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("END DATE :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("START DATE :");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/reserve (2).png"))); // NOI18N
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Startdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Enddate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(Slotcmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vehiclecmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Slotcmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(Vehiclecmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(Startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(Enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(960, 70, 230, 690);

        reserveimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Images/parking-504137_960_720.png"))); // NOI18N
        reserveimg.setMaximumSize(new java.awt.Dimension(32767, 32767));
        reserveimg.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.add(reserveimg);
        reserveimg.setBounds(0, 70, 960, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker Enddate;
    private javax.swing.JComboBox<String> Slotcmbbox;
    private javax.swing.JLabel Slotlbl1;
    private javax.swing.JLabel Slotlbl10;
    private javax.swing.JLabel Slotlbl11;
    private javax.swing.JLabel Slotlbl12;
    private javax.swing.JLabel Slotlbl13;
    private javax.swing.JLabel Slotlbl14;
    private javax.swing.JLabel Slotlbl15;
    private javax.swing.JLabel Slotlbl2;
    private javax.swing.JLabel Slotlbl3;
    private javax.swing.JLabel Slotlbl4;
    private javax.swing.JLabel Slotlbl5;
    private javax.swing.JLabel Slotlbl6;
    private javax.swing.JLabel Slotlbl7;
    private javax.swing.JLabel Slotlbl8;
    private javax.swing.JLabel Slotlbl9;
    private org.jdesktop.swingx.JXDatePicker Startdate;
    private javax.swing.JComboBox<String> Vehiclecmbbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel reserveimg;
    // End of variables declaration//GEN-END:variables
}
