/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronend;
import Backend.Staff;
import Backend.Role;
import Backend.Login;
import Fronend.MessageBox;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Hashtable;
/**
 *
 * @author thisa
 */
public class ChangeStaffPassword extends javax.swing.JFrame {

    /**
     * Creates new form AddStaff
     */
    Backend.Login login = new Backend.Login();

    
    public ChangeStaffPassword() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newpswlbl = new javax.swing.JLabel();
        newpswtxt = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        submitbtn = new javax.swing.JButton();
        unamelbl = new javax.swing.JLabel();
        unametxt = new javax.swing.JTextField();
        chkbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        newpswlbl.setText("New Password");

        newpswtxt.setToolTipText("Minimum 8 characters ");
        newpswtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newpswtxtKeyTyped(evt);
            }
        });

        label1.setText("label1");

        submitbtn.setText("Submit");
        submitbtn.setToolTipText("Submit the new password");
        submitbtn.setEnabled(false);
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        unamelbl.setText("Username");

        unametxt.setToolTipText("Enter the username");

        chkbtn.setText("Check");
        chkbtn.setToolTipText("Check the username on the database");
        chkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newpswlbl)
                            .addComponent(unamelbl))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newpswtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(unametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkbtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(submitbtn)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkbtn)
                    .addComponent(unamelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpswtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newpswlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitbtn)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        
        
        if(login.isUsernameExists(unametxt.getText()) && newpswtxt.getText().length()>=8)
        {
            login.setUsername(unametxt.getText());
            login.setPassword(newpswtxt.getText());
            
            
            if(login.changePassword())
            { MessageBox.infoBox("Username : " + login.getUsername() + "\nNew Password : " + login.getPassword() + "\nPlease make sure to remember these before click OK.", "YOUR CREDENTIALS");
                this.dispose();
            }
            else 
                MessageBox.infoBox("If this issue presists please contact admin.", "Something Went Wrong!!!");  
        }
        else MessageBox.infoBox("Please fill all the required information.", "Fill required fields");  
    }//GEN-LAST:event_submitbtnActionPerformed

    private void chkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbtnActionPerformed
        if(unametxt.getText().length() < 4)
            MessageBox.infoBox("Username is too short. Please make sure at least it has 5 characters.", "Too short");
        else if(chkbtn.getText().equals("Reset"))
        {
            chkbtn.setText("Check");
            submitbtn.setEnabled(false);
            newpswtxt.setEditable(false);
            unametxt.setEditable(true);
            unametxt.setText("");
            newpswtxt.setText("");
        }
        else if(login.isUsernameExists(unametxt.getText()) && chkbtn.getText().equals("Check"))
        {
            
            newpswtxt.setEditable(true);
            unametxt.setEditable(false);
            chkbtn.setText("Reset");
        }
        else 
        {
            submitbtn.setEnabled(false);
            newpswtxt.setEditable(false);
            unametxt.setEditable(true);
            MessageBox.infoBox("Username Does not exists.", "Not found");
            unametxt.setText("");
        }
        
    }//GEN-LAST:event_chkbtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void newpswtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpswtxtKeyTyped
        boolean max = newpswtxt.getText().length() > 7;
        if ( max )
        submitbtn.setEnabled(true);
        else
        submitbtn.setEnabled(false);
    }//GEN-LAST:event_newpswtxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeStaffPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeStaffPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeStaffPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeStaffPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeStaffPassword().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chkbtn;
    private java.awt.Label label1;
    protected javax.swing.JLabel newpswlbl;
    protected javax.swing.JTextField newpswtxt;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel unamelbl;
    private javax.swing.JTextField unametxt;
    // End of variables declaration//GEN-END:variables
}
