/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronend.Staff;

import Fronend.AddRole;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author thisa
 */
public class StaffIF extends javax.swing.JFrame {

    /**
     * Creates new form StaffIF
     * @param ut
     */
    private static String ut="";
    private static String uname="";
    
    public StaffIF(String usertype, String uname) {
        initComponents();
//        mngstaffpanel.setVisible(false);
//        mngrolespanel.setVisible(false);
        ut=usertype;
        UserType.setText(ut);
        
    }
    public StaffIF() {
        initComponents();
//        mngrolespanel.setVisible(false);
//        mngstaffpanel.setVisible(false);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserType = new javax.swing.JLabel();
        mngstaffbtn = new javax.swing.JButton();
        UTlbl = new javax.swing.JLabel();
        mngrolesbtn = new javax.swing.JButton();
        tabpane = new javax.swing.JTabbedPane();
        mngrolespanel = new javax.swing.JPanel();
        addrolebtn = new javax.swing.JButton();
        mngstaffpanel = new javax.swing.JPanel();
        addstaffbtn = new javax.swing.JButton();
        changepswbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        unamelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserType.setText("Usertype");

        mngstaffbtn.setText("Manage Staff");
        mngstaffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngstaffbtnActionPerformed(evt);
            }
        });

        UTlbl.setText("Staff Level : ");

        mngrolesbtn.setText("Manage Roles");
        mngrolesbtn.setToolTipText("");
        mngrolesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngrolesbtnActionPerformed(evt);
            }
        });

        tabpane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addrolebtn.setText("Add a Role");
        addrolebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrolebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mngrolespanelLayout = new javax.swing.GroupLayout(mngrolespanel);
        mngrolespanel.setLayout(mngrolespanelLayout);
        mngrolespanelLayout.setHorizontalGroup(
            mngrolespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mngrolespanelLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(addrolebtn)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        mngrolespanelLayout.setVerticalGroup(
            mngrolespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mngrolespanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(addrolebtn)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        tabpane.addTab("Roles", null, mngrolespanel, "Manage System Roles");

        mngstaffpanel.setName("Staff"); // NOI18N

        addstaffbtn.setText("Add Staff Members");
        addstaffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstaffbtnActionPerformed(evt);
            }
        });

        changepswbtn.setText("Change Password");
        changepswbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepswbtnActionPerformed(evt);
            }
        });

        jButton1.setText("Search Staff");

        javax.swing.GroupLayout mngstaffpanelLayout = new javax.swing.GroupLayout(mngstaffpanel);
        mngstaffpanel.setLayout(mngstaffpanelLayout);
        mngstaffpanelLayout.setHorizontalGroup(
            mngstaffpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mngstaffpanelLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(mngstaffpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changepswbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addstaffbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(235, 235, 235))
        );
        mngstaffpanelLayout.setVerticalGroup(
            mngstaffpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mngstaffpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(addstaffbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changepswbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(458, 458, 458))
        );

        tabpane.addTab("Staff", null, mngstaffpanel, "");

        jLabel1.setText("Username : ");

        unamelbl.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mngstaffbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mngrolesbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UTlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserType))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unamelbl)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserType)
                    .addComponent(UTlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(unamelbl))
                .addGap(64, 64, 64)
                .addComponent(mngstaffbtn)
                .addGap(18, 18, 18)
                .addComponent(mngrolesbtn)
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mngstaffbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngstaffbtnActionPerformed
        tabpane.setSelectedIndex(0);
            
            
        
    }//GEN-LAST:event_mngstaffbtnActionPerformed

    private void mngrolesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngrolesbtnActionPerformed
        tabpane.setSelectedIndex(1);
    }//GEN-LAST:event_mngrolesbtnActionPerformed

    private void addstaffbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstaffbtnActionPerformed
        AddStaff stf = new AddStaff();
        stf.setVisible(true);
    }//GEN-LAST:event_addstaffbtnActionPerformed

    private void addrolebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrolebtnActionPerformed
       AddRole addrl = new AddRole();
        addrl.setVisible(true);
    }//GEN-LAST:event_addrolebtnActionPerformed

    private void changepswbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepswbtnActionPerformed
        ChangeStaffPassword newpsw = new ChangeStaffPassword();
        newpsw.setVisible(true);
        newpsw.newpswlbl.setVisible(false);
    }//GEN-LAST:event_changepswbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffIF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UTlbl;
    private javax.swing.JLabel UserType;
    private javax.swing.JButton addrolebtn;
    private javax.swing.JButton addstaffbtn;
    private javax.swing.JButton changepswbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngrolesbtn;
    private javax.swing.JPanel mngrolespanel;
    private javax.swing.JButton mngstaffbtn;
    private javax.swing.JPanel mngstaffpanel;
    private javax.swing.JTabbedPane tabpane;
    private javax.swing.JLabel unamelbl;
    // End of variables declaration//GEN-END:variables
}
